version: 2.1
orbs:
    codecov: codecov/codecov@1.1.3
jobs:
    build_project:
        working_directory: ~/ionic-design-patterns
        docker:
            - image: circleci/node:14.0.0-browsers
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v2-dependencies-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: |
                    yarn install --frozen-lockfile
            - save_cache:
                name: Save Cache
                paths:
                    - node_modules
                key: v2-dependencies-{{ checksum "yarn.lock" }}
            - run:
                name: Prettier Check
                command: |
                    yarn prettier:check
            - run:
                name: Lint
                command: |
                    yarn lint
            - run:
                name: Unit Tests
                command: |
                    yarn test --no-watch --code-coverage
            - run:
                name: Build Project
                command: |
                    yarn build
            # Save the coverage folder for codecov report upload.
            - persist_to_workspace:
                root: .
                paths:
                    - coverage
    coverage_report:
        working_directory: ~/ionic-design-patterns
        docker:
            - image: circleci/node:14.0.0-browsers
        steps:
            - checkout
            - attach_workspace:
                at: .
            - codecov/upload:
                file: './coverage/lcov.info'
                token: 5ac9f1bc-a0e5-4423-aa0c-83614dae4b9d

workflows:
    version: 2
    ionic_design_patterns:
        jobs:
            - build_project
            - coverage_report:
                requires:
                    - build_project
                filters:
                  branches:
                      only:
                        - master